# Generated by Django 4.0.5 on 2022-09-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritu_web_app', '0038_remove_marketplace_id_alter_marketplace_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
